import NextLink from '@/components/NextLink';
import PokemonSprite from '@/components/PokemonSprite';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Next.js Infinite Loader using SWR</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<nav className='max-w-screen-xl mx-auto px-6 py-10'>
				<ul className='flex justify-between'>
					<li>
						<NextLink className='font-mono text-2xl font-bold tracking-tight text-slate-800'>
							Infinite
						</NextLink>
					</li>
					<li>
						<NextLink
							href='#'
							className='bg-primary text-white py-3 px-6 rounded-md font-bold hover:bg-primary/95 focus-visible:outline-offset-2 focus-visible:outline-pink-300 focus:outline-pink-300 focus:outline-offset-2 drop-shadow-sm'
						>
							Go to
						</NextLink>
					</li>
				</ul>
			</nav>
			<main className='max-w-screen-xl mx-auto px-6'>
				<section className='py-12'>
					<div className='grid gap-x-6 gap-y-8 xs:grid-cols-2 lg:grid-cols-4 '>
						<PokemonSprite />
						<PokemonSprite />
						<PokemonSprite />
						<PokemonSprite />
					</div>
					<div className='centered mt-12'>
						<button className='bg-primary py-4 px-10 font-semibold rounded-md disabled:bg-primary/50 disabled:cursor-not-allowed text-white'>
							Load more
						</button>
					</div>
				</section>
			</main>
		</>
	);
}
